# -*- coding: utf-8 -*-
"""keyword_recipe(최종).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9Dl0SsrQf7hI-kT1ApPpXWGy1-ox4aW
"""


# !pip install konlpy
# !pip install fasttext

'''
pip install openpyxl pandas numpy konlpy gensim tqdm joblib scipy==1.12
'''

import pandas as pd
from ast import literal_eval
from gensim.models import FastText
from gensim import models
import joblib


# 키워드 입력 후 유사도 순으로 정렬된 레시피 반환함수
# keyword 및 cnt(반환개수) 파라미터로 입력
def keyword_recipe(keyword, cnt):

    # 토큰화 데이터 불러오기
    test = pd.read_excel('./model/train_recipe2.xlsx')
    test['token'] = test['token'].apply(literal_eval)

    # 모델 불러오기
    model = joblib.load('./model/saved_model.pkl')

    # 유사도 계산
    test['max_similarity'] = test['token'].apply(lambda tokens: max([model.wv.similarity(keyword, token) for token in tokens]))

    # 상위 cnt개 결과 출력 후 id를 리스트로 반환
    result = test.sort_values(by = 'max_similarity', ascending=False)
    result = result.head(cnt)
    ob_list = list(result['ObjectId'])
    return ob_list

print(keyword_recipe('다이어트', 3))
